_target_: gold.models.GPT_jit.GPTLitModule

learning_rate: 1.0e-3
block_size: ${data.block_size}

model:
  _target_: gold.models.GPT_jit.GPT
  vocab_size: 100277
  block_size: ${data.block_size}
  n_embed: 64
  n_heads: 4
  drop_p: 0.1
  n_decoder_blocks: 2